### ISSUE TITLE
Typo in function explanation

### ISSUE THREAD

**Issue by ronsavage** [tobyink/p5-hydrogen#2]
In Hydrogen::HashRef's accessor, you have: Acts like get if given one argument, or set if given two arguments.
I suspect that should read: Acts like get if given /two/ argument/s/, or set if given /three/ arguments.

**Comment by tobyink** [comment]
Yeah, the documentation is autogenerated from Sub::HandlesVia where one/two makes more sense.

In Sub::HandlesVia you'd define something like:

```perl
package DNS {
  use Moo;
  use Sub::HandlesVia;
  
  has _address_mapping => (
    is          => 'ro',
    default     => sub { {} },
    handles_via => 'Hash',
    handles     => {
      'address'   => 'accessor',
      'clear'     => 'delete',
      'clear_all' => 'clear',
    },
  );
}

my $server = DNS->new;
$server->address( 'foo.example.com', '10.0.0.1' ); # set
say $server->address( 'foo.example.com' );         # get
$server->clear( 'foo.example.com' );
$server->clear_all;
```

So there's one/two arguments plus the invocant. In Hydrogen, the same code is used but as function calls instead of method calls, so the invocant gets flipped into being the first argument, which means we end up with two/three arguments.

But the documentation is also autogenerated from Sub::HandlesVia, so we end up with this.

This is something to be solved, but I want to be able to do it without maintaining two sets of documentation.

**Comment by ronsavage** [comment]
Hi Tony

Ah, yes, I see the issue.

And thanx for the quick reply.

---
Cheers
Ron
savage.net.au

**Comment by tobyink** [comment]
Should be resolved in the latest release
